services:
  web:
    image: odoo
    container_name: odoo
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons 
    environment:
      - HOST=mydb
      - USER=odoo
      - PASSWORD=myodoo
  mydb:
    image: postgres:15.3
    container_name: db
    volumes:
      - postgres_data: /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo

  volume:
    postgres_data:
